export default {
  CYP: 'Cyprus',
  MKD: 'North Macedonia',
  YEM: 'Yemen',
  SXM: 'Sint Maarten',
  MAC: 'Macau',
  NGA: 'Nigeria',
  SOM: 'Somalia',
  MMR: 'Myanmar',
  LBR: 'Liberia',
  DMA: 'Dominica',
  KNA: 'Saint Kitts and Nevis',
  PRK: 'North Korea',
  SAU: 'Saudi Arabia',
  NPL: 'Nepal',
  VEN: 'Venezuela',
  GUM: 'Guam',
  BMU: 'Bermuda',
  KEN: 'Kenya',
  CMR: 'Cameroon',
  RWA: 'Rwanda',
  MRT: 'Mauritania',
  NCL: 'New Caledonia',
  FJI: 'Fiji',
  ARG: 'Argentina',
  BRN: 'Brunei',
  NIC: 'Nicaragua',
  GBR: 'United Kingdom',
  LAO: 'Laos',
  MHL: 'Marshall Islands',
  UKR: 'Ukraine',
  IMN: 'Isle of Man',
  KWT: 'Kuwait',
  ATG: 'Antigua and Barbuda',
  NLD: 'Netherlands',
  PLW: 'Palau',
  NZL: 'New Zealand',
  COG: 'Republic of the Congo',
  VGB: 'British Virgin Islands',
  BHR: 'Bahrain',
  BOL: 'Bolivia',
  TGO: 'Togo',
  UZB: 'Uzbekistan',
  BHS: 'Bahamas',
  MDV: 'Maldives',
  TKM: 'Turkmenistan',
  URY: 'Uruguay',
  BGR: 'Bulgaria',
  LSO: 'Lesotho',
  SPM: 'Saint Pierre and Miquelon',
  CUB: 'Cuba',
  HTI: 'Haiti',
  MLT: 'Malta',
  TON: 'Tonga',
  FLK: 'Falkland Islands',
  ETH: 'Ethiopia',
  SSD: 'South Sudan',
  TUN: 'Tunisia',
  PRI: 'Puerto Rico',
  ECU: 'Ecuador',
  CPV: 'Cape Verde',
  MCO: 'Monaco',
  TJK: 'Tajikistan',
  BWA: 'Botswana',
  BVT: 'Bouvet Island',
  IDN: 'Indonesia',
  EST: 'Estonia',
  QAT: 'Qatar',
  CYM: 'Cayman Islands',
  HRV: 'Croatia',
  ZMB: 'Zambia',
  GLP: 'Guadeloupe',
  ROU: 'Romania',
  FRO: 'Faroe Islands',
  MDA: 'Moldova',
  NIU: 'Niue',
  WLF: 'Wallis and Futuna',
  PCN: 'Pitcairn Islands',
  BRB: 'Barbados',
  BIH: 'Bosnia and Herzegovina',
  KOR: 'South Korea',
  BFA: 'Burkina Faso',
  SLV: 'El Salvador',
  SYR: 'Syria',
  COL: 'Colombia',
  BGD: 'Bangladesh',
  MTQ: 'Martinique',
  FSM: 'Micronesia',
  SWE: 'Sweden',
  HUN: 'Hungary',
  ATF: 'French Southern and Antarctic Lands',
  NRU: 'Nauru',
  IRQ: 'Iraq',
  POL: 'Poland',
  NER: 'Niger',
  GRC: 'Greece',
  TZA: 'Tanzania',
  MAR: 'Morocco',
  LIE: 'Liechtenstein',
  TLS: 'Timor-Leste',
  ERI: 'Eritrea',
  MYT: 'Mayotte',
  FRA: 'France',
  HND: 'Honduras',
  WSM: 'Samoa',
  GRL: 'Greenland',
  UNK: 'Kosovo',
  AIA: 'Anguilla',
  SRB: 'Serbia',
  SVK: 'Slovakia',
  HMD: 'Heard Island and McDonald Islands',
  KIR: 'Kiribati',
  MSR: 'Montserrat',
  ESP: 'Spain',
  BLZ: 'Belize',
  SYC: 'Seychelles',
  ESH: 'Western Sahara',
  GIB: 'Gibraltar',
  THA: 'Thailand',
  VNM: 'Vietnam',
  SHN: 'Saint Helena, Ascension and Tristan da Cunha',
  AUT: 'Austria',
  VCT: 'Saint Vincent and the Grenadines',
  AND: 'Andorra',
  SJM: 'Svalbard and Jan Mayen',
  NFK: 'Norfolk Island',
  SUR: 'Suriname',
  MNG: 'Mongolia',
  BTN: 'Bhutan',
  SLE: 'Sierra Leone',
  KHM: 'Cambodia',
  DZA: 'Algeria',
  GAB: 'Gabon',
  AFG: 'Afghanistan',
  ARM: 'Armenia',
  LCA: 'Saint Lucia',
  TUV: 'Tuvalu',
  TCA: 'Turks and Caicos Islands',
  GNQ: 'Equatorial Guinea',
  SDN: 'Sudan',
  ATA: 'Antarctica',
  STP: 'São Tomé and Príncipe',
  SVN: 'Slovenia',
  HKG: 'Hong Kong',
  REU: 'Réunion',
  MAF: 'Saint Martin',
  LVA: 'Latvia',
  GUF: 'French Guiana',
  PAK: 'Pakistan',
  AZE: 'Azerbaijan',
  COM: 'Comoros',
  OMN: 'Oman',
  SEN: 'Senegal',
  VIR: 'United States Virgin Islands',
  GHA: 'Ghana',
  CAF: 'Central African Republic',
  SGS: 'South Georgia',
  ASM: 'American Samoa',
  ISR: 'Israel',
  ZWE: 'Zimbabwe',
  BDI: 'Burundi',
  GNB: 'Guinea-Bissau',
  MWI: 'Malawi',
  USA: 'United States',
  PAN: 'Panama',
  MDG: 'Madagascar',
  GEO: 'Georgia',
  PRT: 'Portugal',
  MLI: 'Mali',
  COK: 'Cook Islands',
  ISL: 'Iceland',
  TCD: 'Chad',
  TUR: 'Turkey',
  CXR: 'Christmas Island',
  CRI: 'Costa Rica',
  LTU: 'Lithuania',
  CCK: 'Cocos (Keeling) Islands',
  IND: 'India',
  EGY: 'Egypt',
  JEY: 'Jersey',
  VAT: 'Vatican City',
  ZAF: 'South Africa',
  JAM: 'Jamaica',
  BRA: 'Brazil',
  DNK: 'Denmark',
  BEL: 'Belgium',
  PRY: 'Paraguay',
  KAZ: 'Kazakhstan',
  NAM: 'Namibia',
  CIV: 'Ivory Coast',
  MUS: 'Mauritius',
  PSE: 'Palestine',
  MNE: 'Montenegro',
  IOT: 'British Indian Ocean Territory',
  MYS: 'Malaysia',
  DJI: 'Djibouti',
  SLB: 'Solomon Islands',
  GUY: 'Guyana',
  CUW: 'Curaçao',
  KGZ: 'Kyrgyzstan',
  PHL: 'Philippines',
  PNG: 'Papua New Guinea',
  TTO: 'Trinidad and Tobago',
  LBY: 'Libya',
  ABW: 'Aruba',
  RUS: 'Russia',
  DEU: 'Germany',
  GRD: 'Grenada',
  CAN: 'Canada',
  PYF: 'French Polynesia',
  SWZ: 'Eswatini',
  IRN: 'Iran',
  JPN: 'Japan',
  CHN: 'China',
  BLM: 'Saint Barthélemy',
  AGO: 'Angola',
  IRL: 'Ireland',
  NOR: 'Norway',
  MOZ: 'Mozambique',
  JOR: 'Jordan',
  SMR: 'San Marino',
  GMB: 'Gambia',
  SGP: 'Singapore',
  CHL: 'Chile',
  UMI: 'United States Minor Outlying Islands',
  BEN: 'Benin',
  LKA: 'Sri Lanka',
  BLR: 'Belarus',
  BES: 'Caribbean Netherlands',
  PER: 'Peru',
  GGY: 'Guernsey',
  ALA: 'Åland Islands',
  DOM: 'Dominican Republic',
  TKL: 'Tokelau',
  ARE: 'United Arab Emirates',
  AUS: 'Australia',
  GTM: 'Guatemala',
  LBN: 'Lebanon',
  LUX: 'Luxembourg',
  ALB: 'Albania',
  VUT: 'Vanuatu',
  COD: 'DR Congo',
  MNP: 'Northern Mariana Islands',
  CZE: 'Czechia',
  ITA: 'Italy',
  UGA: 'Uganda',
  CHE: 'Switzerland',
  MEX: 'Mexico',
  TWN: 'Taiwan',
  GIN: 'Guinea',
  FIN: 'Finland'
}